### ISSUE TITLE
Issue about errno when using WASI

### ISSUE THREAD

**Issue by lhespress** [WebAssembly/wasi-sdk#241] opened 2022-06-30 09:16 UTC
I am testing the WASI by thread example, and find an issue about `errno`, my steps are following:

```
wasi-sdk-14.0/bin/clang -O3 -mbulk-memory -matomics -ftls-model=local-exec -pthread -z stack-size=8192 -Wl,--initial-memory=65536 -Wl,--shared-memory -Wl,--no-entry -Wl,--allow-undefined -Wl,--strip-all -Wl,--export=main -o thread.wasm thread.c
```

The result is `relocation R_WASM_MEMORY_ADDR_TLS_SLEB cannot be used against `errno` in non-TLS section: .bss`. 

My thread code is following:

```
#include <stdio.h>
#include <errno.h>

int main(void)
{
    errno = 21;
    printf("thread exit %d\n", errno);

    return 0;
}
```

**Comment by sbc100** [comment] 2022-06-30 09:56
This is most likely because non of the wasi-sdk core libraries such as libc and libc++ and compiler-rt are compiled with threading support.

In order to experiment with threading you would need to rebuild the whole SDK with `-pthread` in the cflags.

Also, you don't need `-mbulk-memory -matomics` since those should be implied by `-pthread`.  I'm pretty sure the same is true for `-ftls-model=local-exec`.  Just `-pthread` should be sufficient.

**Comment by lhespress** [comment] 2022-06-30 13:16
@sbc100 when i remove `-mbulk-memory -matomics -ftls-model=local-exec`,  like this: 

```
wasi-sdk-14.0/bin/clang -O3 -pthread -z stack-size=8192 -Wl,--initial-memory=65536 -Wl,--shared-memory -Wl,--no-entry -Wl,--allow-undefined -Wl,--strip-all -Wl,--export=main -o src/thread.wasm src/thread.c
```

it shows the error `only -ftls-model=local-exec is supported for now on non-Emscripten OSes: variable errno`

**Comment by sbc100** [comment] 2022-06-30 13:22
Ok, so `-ftls-model=local-exec` is needed for now that, but the other two should are not.

**Comment by sbc100** [comment] 2022-06-30 13:24
I guess this is really a duplicate of https://github.com/WebAssembly/WASI/issues/296 and can probably be closes as such?

**Comment by sunfishcode** [comment] 2022-07-26 23:02
Yes, this is being pursued in https://reviews.llvm.org/D130053 and https://github.com/WebAssembly/wasi-libc/pull/307.

**Closed by sunfishcode** 2022-07-26 23:02 UTC

**Comment by vapier** [comment] 2024-08-30 19:42
> In order to experiment with threading you would need to rebuild the whole SDK with -pthread in the cflags.

this still seems to be the case with wasi-sdk-24. if that flag is required for correct behavior when using the new wasi threads target, shouldn't it be implied automatically?

**Comment by yamt** [comment] 2024-09-02 06:24
> > In order to experiment with threading you would need to rebuild the whole SDK with -pthread in the cflags.
> 
> this still seems to be the case with wasi-sdk-24. if that flag is required for correct behavior when using the new wasi threads target, shouldn't it be implied automatically?

you don't need to "rebuild the whole SDK" as the recent wasi-sdk ships wasi-threads build of the libraries.

**Comment by vapier** [comment] 2024-09-02 10:19
sorry, meant to emphasize the consistent usage of the flag, not rebuilding the sdk. if you use the threads target but not the pthreads flag, things will link, but you end up with multiple errno storage as described in this report. so if the pthreads flag is required, why isn't it implied when using the threads target?
